/**
 * Immediate Action Summary Box — AEO-optimized callout.
 *
 * Renders a visually distinct summary box that:
 * 1. Appears within the first 2 scroll-lengths of the page
 * 2. Contains a 75–100 word self-contained factual summary
 * 3. Is structured for AI Overview / Answer Engine parsing
 * 4. Uses <blockquote> + microdata for semantic clarity
 *
 * The actual summary text is generated by the AI as part of the blog
 * content (inside a Markdown blockquote). This component provides the
 * styled wrapper when the content is rendered.
 *
 * If you need to inject a summary separately (not from Markdown),
 * use the explicit <AISummaryBox summary="..." /> variant.
 */

interface AISummaryBoxProps {
  /** The 75–100 word summary text. If not provided, the component
   *  renders nothing (the Markdown blockquote handles it). */
  summary?: string;
  /** Weather mode label for context */
  mode?: "pre-event" | "post-event" | "combined";
}

export default function AISummaryBox({ summary, mode }: AISummaryBoxProps) {
  if (!summary) return null;

  const modeLabel =
    mode === "post-event"
      ? "⚠️ Post-Storm Advisory"
      : mode === "combined"
        ? "⚠️ Urgent Weather Advisory"
        : "🌦️ Weather Preparation Advisory";

  return (
    <div
      className="ai-summary-box my-8 rounded-lg border-l-4 border-brand-orange bg-brand-orange-light p-6"
      itemScope
      itemType="https://schema.org/Article"
    >
      <div className="mb-2 text-xs font-semibold uppercase tracking-wider text-brand-orange">
        {modeLabel}
      </div>
      <h3 className="mb-3 text-lg font-bold text-brand-dark">
        Immediate Action Summary for Muncie Homeowners
      </h3>
      <p
        className="text-base leading-relaxed text-brand-dark-secondary"
        itemProp="abstract"
      >
        {summary}
      </p>
    </div>
  );
}
